logfile = "" # log file location
loglevel = "DEBUG" # CRITICAL|ERROR|WARNING|NOTICE|INFO|DEBUG
accesslog = "" # http access log file
httpaddr = "192.168.88.143:443"
http3addr = "192.168.88.143:443"
httpaddrext = "https://192.168.88.143:443/"
http3addrext = "https://192.168.88.143:443/"
certpem = "auto"
keypem = ""
staticcachecontrol = "max-age=31968000, s-maxage=864000, stale-while-revalidate=86400, public"
jwtkey = "geheim"
jwtalg = ["HS256","HS384","HS512"]
linktokenexp = "1h"
prefix = "/media"
staticprefix = "/static"
mediaprefix = "/media"
staticfolder = "C:\\daten\\go\\dev\\zmedia\\web\\static"

[[filemap]]
    alias = "static"
    folder = "/mnt/daten/go/dev/zmedia/web/static"

[dbold]
    servertype = "mysql"
    # dsn = "mediaserver:kn6Iy4mLuzH7HWPo@tcp(v000306.adm.ds.fhnw.ch:3306)/mediaserver?charset=utf8"
    dsn = "mediaserver:kn6Iy4mLuzH7HWPo@tcp(localhost:3306)/mediaserver?charset=utf8"
    connection_max = 5000
    schema = "mediaserver"

[db]
    servertype = "postgres"
    dsn = "postgres://media:GPj2uO9avtGMJWXp@localhost:5433/media"
    connection_max = 5000
    schema = "public"


[[s3]]
    name = "hgk"
    endpoint = "minio.campusderkuenste.ch"
    accessKeyId = "media"
    secretAccessKey = "DzqApK0rK7tRlbKlBG2JymDJeHvPMfOd"
    useSSL = true

[sshtunnel]
    user = "root"
    privatekey = "/mnt/daten/keys/putty_ed25519.priv.openssh"
    [sshtunnel.localendpoint]
        port = 5433
        host = "localhost"

    [sshtunnel.serverendpoint]
        port = 22
        host = "ba14ns21403.fhnw.ch"

    [sshtunnel.remoteendpoint]
        port = 5432
        host = "v000306.adm.ds.fhnw.ch"
